### ISSUE TITLE
grunt not working

### ISSUE THREAD

**Issue by kennedyabitbol** [clean-docker/Magento2#79]
Hi,

When i run a grunt command i got an eror:

root@44970b305679:/var/www/html# grunt
module.js:478
    throw err;
    ^

Error: Cannot find module 'abbrev'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/grunt-cli/node_modules/nopt/lib/nopt.js:10:14)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)

I there somthin missing?

Thank you,
Damien.

**Comment by kennedyabitbol** [comment]
update globally grunt-cli did the works, by the way discovered a great https://www.npmjs.com/package/npm-check-updates
